
- layer: bronze
  source_type: fabric_connection
  connection_name: sqlserver_contracts
  source_table: contracts
  table_name: contracts
  key_1: code
  key_2: null
  date_column: updated_at
  partition_cols: 
  columns:
    - column_name: Gender
      type: string
      tests: 
        - name: not_null
        - name: not_duplicated
        - name: in_list
          kwargs: 
            expected_values: [Male, Female]
    - column_name: Code
      type: string
      tests: 
        - name: not_null
        - name: not_duplicated
    - column_name: Status
      type: string
      tests: 
        - name: not_null
        - name: in_list
          kwargs:
            expected_values: [Active, Inactive] 
    - column_name: 'Crop Type'
      type: string
      tests: 
        - name: not_null
        - name: in_list
          kwargs:
            expected_values: ['Flue Cured', 'Broadleaf', 'Burley']
          


